name                      = "exampleA"
projectroot               = "example"
description               = "Description fitting of such a repos"
force_artifact_destroy    = "false"
build_timeout             = "60"
